[MeterClock0]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*0))
RotationAngle=(Rad(360))
LineWidth=(0 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(0 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock1]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*1))
RotationAngle=(Rad(360))
LineWidth=(1 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(1 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock2]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*2))
RotationAngle=(Rad(360))
LineWidth=(2 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(2 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock3]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*3))
RotationAngle=(Rad(360))
LineWidth=(3 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(3 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock4]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*4))
RotationAngle=(Rad(360))
LineWidth=(4 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(4 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock5]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*5))
RotationAngle=(Rad(360))
LineWidth=(5 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(5 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock6]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*6))
RotationAngle=(Rad(360))
LineWidth=(6 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(6 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock7]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*7))
RotationAngle=(Rad(360))
LineWidth=(7 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(7 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock8]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*8))
RotationAngle=(Rad(360))
LineWidth=(8 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(8 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock9]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*9))
RotationAngle=(Rad(360))
LineWidth=(9 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(9 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock10]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*10))
RotationAngle=(Rad(360))
LineWidth=(10 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(10 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock11]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*11))
RotationAngle=(Rad(360))
LineWidth=(11 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(11 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock12]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*12))
RotationAngle=(Rad(360))
LineWidth=(12 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(12 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock13]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*13))
RotationAngle=(Rad(360))
LineWidth=(13 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(13 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock14]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*14))
RotationAngle=(Rad(360))
LineWidth=(14 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(14 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock15]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*15))
RotationAngle=(Rad(360))
LineWidth=(15 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(15 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock16]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*16))
RotationAngle=(Rad(360))
LineWidth=(16 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(16 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock17]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*17))
RotationAngle=(Rad(360))
LineWidth=(17 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(17 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock18]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*18))
RotationAngle=(Rad(360))
LineWidth=(18 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(18 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock19]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*19))
RotationAngle=(Rad(360))
LineWidth=(19 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(19 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock20]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*20))
RotationAngle=(Rad(360))
LineWidth=(20 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(20 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock21]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*21))
RotationAngle=(Rad(360))
LineWidth=(21 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(21 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock22]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*22))
RotationAngle=(Rad(360))
LineWidth=(22 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(22 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock23]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*23))
RotationAngle=(Rad(360))
LineWidth=(23 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(23 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock24]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*24))
RotationAngle=(Rad(360))
LineWidth=(24 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(24 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock25]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*25))
RotationAngle=(Rad(360))
LineWidth=(25 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(25 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock26]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*26))
RotationAngle=(Rad(360))
LineWidth=(26 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(26 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock27]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*27))
RotationAngle=(Rad(360))
LineWidth=(27 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(27 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock28]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*28))
RotationAngle=(Rad(360))
LineWidth=(28 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(28 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock29]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*29))
RotationAngle=(Rad(360))
LineWidth=(29 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(29 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock30]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*30))
RotationAngle=(Rad(360))
LineWidth=(30 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(30 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock31]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*31))
RotationAngle=(Rad(360))
LineWidth=(31 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(31 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock32]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*32))
RotationAngle=(Rad(360))
LineWidth=(32 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(32 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock33]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*33))
RotationAngle=(Rad(360))
LineWidth=(33 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(33 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock34]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*34))
RotationAngle=(Rad(360))
LineWidth=(34 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(34 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock35]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*35))
RotationAngle=(Rad(360))
LineWidth=(35 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(35 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock36]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*36))
RotationAngle=(Rad(360))
LineWidth=(36 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(36 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock37]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*37))
RotationAngle=(Rad(360))
LineWidth=(37 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(37 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock38]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*38))
RotationAngle=(Rad(360))
LineWidth=(38 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(38 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock39]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*39))
RotationAngle=(Rad(360))
LineWidth=(39 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(39 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock40]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*40))
RotationAngle=(Rad(360))
LineWidth=(40 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(40 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock41]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*41))
RotationAngle=(Rad(360))
LineWidth=(41 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(41 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock42]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*42))
RotationAngle=(Rad(360))
LineWidth=(42 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(42 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock43]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*43))
RotationAngle=(Rad(360))
LineWidth=(43 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(43 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock44]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*44))
RotationAngle=(Rad(360))
LineWidth=(44 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(44 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock45]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*45))
RotationAngle=(Rad(360))
LineWidth=(45 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(45 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock46]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*46))
RotationAngle=(Rad(360))
LineWidth=(46 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(46 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock47]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*47))
RotationAngle=(Rad(360))
LineWidth=(47 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(47 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock48]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*48))
RotationAngle=(Rad(360))
LineWidth=(48 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(48 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock49]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*49))
RotationAngle=(Rad(360))
LineWidth=(49 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(49 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock50]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*50))
RotationAngle=(Rad(360))
LineWidth=(50 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(50 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock51]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*51))
RotationAngle=(Rad(360))
LineWidth=(51 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(51 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock52]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*52))
RotationAngle=(Rad(360))
LineWidth=(52 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(52 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock53]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*53))
RotationAngle=(Rad(360))
LineWidth=(53 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(53 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock54]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*54))
RotationAngle=(Rad(360))
LineWidth=(54 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(54 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock55]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*55))
RotationAngle=(Rad(360))
LineWidth=(55 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(55 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock56]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*56))
RotationAngle=(Rad(360))
LineWidth=(56 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(56 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock57]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*57))
RotationAngle=(Rad(360))
LineWidth=(57 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(57 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock58]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*58))
RotationAngle=(Rad(360))
LineWidth=(58 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(58 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1
[MeterClock59]
Meter=Roundline
X=(0.75*135)
Y=(0.75*135)
StartAngle=(Rad(270 + (360/60)*59))
RotationAngle=(Rad(360))
LineWidth=(59 % 5 = 0 ? (3*0.75) : (2*0.75))
LineStart=(59 % 5 = 0 ? (90*0.75) : (100*0.75))
LineLength=(105*0.75)
AntiAlias=1
DynamicVariables=1
LineColor=#cClock#
UpdateDivider=-1